name: Deploy Production
on:
  push:
    branches:
    - master
jobs:
  build: 
    name: Build and Deploy via SSH
    runs-on: ubuntu-latest
    steps:
    - name: SSH Comands to Server
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        user: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY}}
        command: cd /home/webdev/Web/maucoding.com && git pull origin && rm -rf node_modules && npm install && npm run build:prod && pm2 restart mc